# Generated by Django 3.1.4 on 2020-12-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularplan',
            name='cycle',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10, verbose_name='Cycle'),
        ),
    ]
